### ISSUE TITLE
netherite jetpack?

### ISSUE THREAD

**Issue by poly-1810** [PssbleTrngle/CreateJetpack#74] opened 2023-07-08 22:05 UTC
### Describe the feature you have in mind.

just a netherite jetpack for diving in lava, pretty sure this has been requested before
also, please make it available for create 0.5.1b, 1.18.2, amongst other versions so that it can be usable for modpacks 

### Does this solve a particular problem?

allows us to dive in lava with jetpack enabled, if using the netherite jetpack

**Comment by PssbleTrngle** [comment] 2023-07-09 17:11
Duplicate of #61.
I'm still thinking about it, but all new features will definitely only be implemented against the newest version of create

**Closed as not planned by PssbleTrngle** 2023-07-09 17:11 UTC
Labels: enhancement
