### ISSUE TITLE
Jetpack Boost Not working 1.19.2

### ISSUE THREAD

**Issue by GamerTable** [PssbleTrngle/CreateJetpack#85] opened 2023-11-30 00:34 UTC
### What happened?

The Jetpack boost is not working while using Elytra or Swimming
However, hover mode does work while swimming

### Loader

fabric

### Mod Version

3.3.1

### Minecraft Version

1.19

**Comment by PssbleTrngle** [comment] 2023-12-14 23:24
duplicate of #82

**Closed as not planned by PssbleTrngle** 2023-12-14 23:24 UTC
Labels: bug, duplicate
